art/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import art.views as views

app_name = 'art'

urlpatterns = [
    # Music front page
    path(
        '',
        views.ArtPageView.as_view(),
        name="art_page",
    ),
    # Art app profile
    ## Update
    path(
        'profile/update/<int:pk>/', 
        views.ArtAppProfileUpdateView.as_view(),
        name='art_app_profile_update',
    ),
    # Art landing page section views
    ## Create
    path(
        'add/section/', 
        views.ArtPageSectionCreateView.as_view(),
        name='art_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/', 
        views.ArtPageSectionDetailView.as_view(),
        name='art_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.ArtPageSectionUpdateView.as_view(),
        name='art_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/', 
        views.ArtPageSectionDeleteView.as_view(),
        name='art_page_section_delete',
    ),
    # Read Views
    path(
        'galleries/new/',
        views.GalleryListView.as_view(),
        name='new_galleries',
    ),
    path(
        'galleries/',
        views.TopGalleryListView.as_view(),
        name='top_galleries',
    ),
    path(
        'galleries/<slug:slug>/',
        views.GalleryDetailView.as_view(),
        name='gallery_detail',
    ),
    path(
        'visuals/new/',
        views.VisualListView.as_view(),
        name='new_visuals',
    ),
    path(
        'visuals/',
        views.TopVisualListView.as_view(),
        name='top_visuals',
    ),
    path(
        'visuals/<slug:slug>/',
        views.VisualDetailView.as_view(),
        name='visual_detail',
    ),
    path(
        'member/<slug:member>/galleries/',
        views.MemberGalleryView.as_view(),
        name='member_galleries',
    ),
    path(
        'studio/galleries/',
        views.GalleryStudioListView.as_view(),
        name='gallery_studio_list',
    ),
    path(
        'member/<slug:member>/visuals/',
        views.MemberVisualView.as_view(),
        name='member_visuals',
    ),
    path(
        'studio/articles/',
        views.VisualStudioListView.as_view(),
        name='visual_studio_list',
    ),
    # Create Views
    path(
        'add/gallery/',
        views.GalleryCreateView.as_view(),
        name='gallery_create',
    ),
    path(
        'add/visual/',
        views.VisualCreateView.as_view(),
        name='visual_create',
    ),
    # Update Views
    path(
        'modify/gallery/<slug:slug>/',
        views.GalleryUpdateView.as_view(),
        name='gallery_update',
    ),
    path(
        'modify/visual/<slug:slug>/',
        views.VisualUpdateView.as_view(),
        name='visual_update',
    ),
    # Delete Views
    path(
        'delete/gallery/<int:pk>/',
        views.GalleryDeleteView.as_view(),
        name='gallery_delete',
    ),
    path(
        'delete/visual/<int:pk>/',
        views.VisualDeleteView.as_view(),
        name='visual_delete',
    ),
    # Publish Views
    path(
        'publish/gallery/<int:pk>/',
        views.publish_gallery_view,
        name='publish_gallery',
    ),
    path(
        'publish/visual/<int:pk>/',
        views.publish_visual_view,
        name='publish_visual',
    ),
    # Marshmallow Views
    path(
        'galleries/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_gallery_view,
        name='gallery_marshmallow',
    ),
    path(
        'visuals/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_visual_view,
        name='visual_marshmallow',
    ),
]

home/urls.py
from django.urls import path
import home.views as views

app_name = 'home'

urlpatterns = [
    # Landing page
    path('', views.IndexView.as_view(), name='index'),
    # Home app profile
    ## Update
    path(
        'profile/update/<int:pk>/site/settings/', 
        views.SiteProfileUpdateView.as_view(),
        name='site_profile_update',
    ),
    path(
        'profile/update/<int:pk>/', 
        views.HomeAppProfileUpdateView.as_view(),
        name='home_app_profile_update',
    ),
    path(
        'profile/update/<int:pk>/settings/', 
        views.HomeAppProfileSettingsUpdateView.as_view(),
        name='home_app_profile_settings_update',
    ),
    # Home landing page section views
    ## Create
    path(
        'add/section/', 
        views.HomePageSectionCreateView.as_view(),
        name='home_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.HomePageSectionDetailView.as_view(),
        name='home_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.HomePageSectionUpdateView.as_view(),
        name='home_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.HomePageSectionDeleteView.as_view(),
        name='home_page_section_delete',
    ),
]

members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
import members.views as views

app_name = "members"
urlpatterns = [
    # Members landing page
    path(
        '',
        views.MembersPageView.as_view(),
        name="members_page",
    ),
    # Members app profile
    ## Update
    path(
        'app-profile/update/<int:pk>/', 
        views.MembersAppProfileUpdateView.as_view(),
        name='members_app_profile_update',
    ),
    # Members landing page section views
    ## Create
    path(
        'add/section/', 
        views.MembersPageSectionCreateView.as_view(),
        name='members_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.MembersPageSectionDetailView.as_view(),
        name='members_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.MembersPageSectionUpdateView.as_view(),
        name='members_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.MembersPageSectionDeleteView.as_view(),
        name='members_page_section_delete',
    ),
    # Member profile
    ## Update
    path(
        'profile/update/<int:pk>/',
        views.MemberProfileUpdateView.as_view(),
        name='member_profile_update',
    ),
    path(
        'profile/settings/update/<int:pk>/',
        views.MemberProfileSettingsUpdateView.as_view(),
        name='member_profile_settings_update',
    ),
    # Member profile page section views
    ## Create
    path(
        'profile/add/section/',
        views.MemberProfileSectionCreateView.as_view(),
        name='member_profile_section_create',
    ),
    ## Detail
    path(
        'profile/sections/<int:pk>/',
        views.MemberProfileSectionDetailView.as_view(),
        name='member_profile_section_detail',
    ),
    ## Update
    path(
        'profile/update/section/<int:pk>/', 
        views.MemberProfileSectionUpdateView.as_view(),
        name='member_profile_section_update',
    ),
    ## Delete
    path(
        'profile/delete/section/<int:pk>/',
        views.MemberProfileSectionDeleteView.as_view(),
        name='member_profile_section_delete',
    ),
    ## List
    path(
        'all/', 
        views.MemberListView.as_view(),
        name='member_list',
    ),
    path(
        'contributors/', 
        views.ContributorListView.as_view(),
        name='contributor_list',
    ),
    path(
        'artists/', 
        views.ArtistListView.as_view(),
        name='artist_list',
    ),
    path(
        'musicians/', 
        views.MusicianListView.as_view(),
        name='musician_list',
    ),
    path(
        'writers/', 
        views.WriterListView.as_view(),
        name='writer_list',
    ),
    path(
        'staff/', 
        views.StaffListView.as_view(),
        name='staff_list',
    ),
    # Studio
    path(
        'studio/',
        views.StudioView.as_view(),
        name='studio',
    ),
    path(
        '<slug:slug>/profile/', 
        views.MemberProfileUpdateView.as_view(),
        name='member_profile_update',
    ),
    path(
        'join-us/<slug:slug>/', 
        views.InviteLinkDetailView.as_view(),
        name='invite_link_detail',
    ),
    path(
        'register/<slug:invite>/', 
        views.member_registration,
        name='member_registration',
    ),
    # Profile page
    path(
        '<slug:slug>/', 
        views.MemberProfileView.as_view(),
        name='member_profile',
    ),
]

music/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import music.views as views  

app_name = 'music'

urlpatterns = [
    # Music landing page
    path(
        '',
        views.MusicPageView.as_view(),
        name="music_page",
    ),
    # Music app profile
    ## Update
    path(
        'profile/update/<int:pk>/', 
        views.MusicAppProfileUpdateView.as_view(),
        name='music_app_profile_update',
    ),
    # Music landing page section views
    ## Create
    path(
        'add/section/', 
        views.MusicPageSectionCreateView.as_view(),
        name='music_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.MusicPageSectionDetailView.as_view(),
        name='music_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.MusicPageSectionUpdateView.as_view(),
        name='music_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.MusicPageSectionDeleteView.as_view(),
        name='music_page_section_delete',
    ),
    # Read Views
    path(
        'albums/new/',
        views.AlbumListView.as_view(),
        name='new_albums',
    ),
    path(
        'albums/',
        views.TopAlbumListView.as_view(),
        name='top_albums',
    ),
    path(
        'albums/<slug:slug>/',
        views.AlbumDetailView.as_view(),
        name='album_detail',
    ),
    path(
        'tracks/new/',
        views.TrackListView.as_view(),
        name='new_tracks',
    ),
    path(
        'tracks/',
        views.TopTrackListView.as_view(),
        name='top_tracks',
    ),
    path(
        'tracks/<slug:slug>/',
        views.TrackDetailView.as_view(),
        name='track_detail',
    ),
    path(
        'member/<slug:member>/albums/',
        views.MemberAlbumView.as_view(),
        name='member_albums',
    ),
    path(
        'studio/albums/',
        views.AlbumStudioListView.as_view(),
        name='album_studio_list',
    ),
    path(
        'member/<slug:member>/tracks/',
        views.MemberTrackView.as_view(),
        name='member_tracks',
    ),
    path(
        'studio/tracks/',
        views.TrackStudioListView.as_view(),
        name='track_studio_list',
    ),
    # Create Views
    path(
        'add/album/',
        views.AlbumCreateView.as_view(),
        name='album_create',
    ),
    path(
        'add/track/',
        views.TrackCreateView.as_view(),
        name='track_create',
    ),
    # Update Views
    path(
        'modify/album/<slug:slug>/',
        views.AlbumUpdateView.as_view(),
        name='album_update',
    ),
    path(
        'modify/track/<slug:slug>/',
        views.TrackUpdateView.as_view(),
        name='track_update',
    ),
    # Delete Views
    path(
        'delete/album/<int:pk>/',
        views.AlbumDeleteView.as_view(),
        name='album_delete',
    ),
    path(
        'delete/track/<int:pk>/',
        views.TrackDeleteView.as_view(),
        name='track_delete',
    ),
    # Publish Views
    path(
        'publish/album/<int:pk>/',
        views.publish_album_view,
        name='publish_album',
    ),
    path(
        'publish/track/<int:pk>/',
        views.publish_track_view,
        name='publish_track',
    ),
    # Marshmallow Views
    path(
        'albums/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_album_view,
        name='album_marshmallow',
    ),
    path(
        'tracks/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_track_view,
        name='track_marshmallow',
    ),
]

posts/urls.py
from django.urls import path
import posts.views as views

app_name= "posts"

urlpatterns = [
    # Posts landing page
    path(
        '',
        views.PostsPageView.as_view(),
        name="posts_page",
    ),
    # Posts app profile
    ## Update
    path(
        'profile/update/<int:pk>/',
        views.PostsAppProfileUpdateView.as_view(),
        name='posts_app_profile_update',
    ),
    # Posts landing page section views
    ## Create
    path(
        'add/section/',
        views.PostsPageSectionCreateView.as_view(),
        name='posts_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.PostsPageSectionDetailView.as_view(),
        name='posts_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/',
        views.PostsPageSectionUpdateView.as_view(),
        name='posts_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.PostsPageSectionDeleteView.as_view(),
        name='posts_page_section_delete',
    ),
    # Read Views
    path(
        'new/', 
        views.PostListView.as_view(),
        name='public_posts',
    ),
    path(
        'top/', 
        views.TopPostListView.as_view(),
        name='top_posts',
    ),
    path(
        'responses/', 
        views.ResponsePostListView.as_view(),
        name='public_responses',
    ),
    path(
        'responses/top/', 
        views.TopResponsePostListView.as_view(),
        name='top_responses',
    ),
    path(
        'reports/', 
        views.ReportPostListView.as_view(),
        name='reports',
    ),
    path(
        '<slug:slug>/', 
        views.PostDetailView.as_view(),
        name='post_detail',
    ),
    path(
        'responses/<slug:slug>/', 
        views.ResponsePostDetailView.as_view(),
        name='response_detail',
    ),
    path(
        'reports/<int:pk>/', 
        views.ReportPostDetailView.as_view(),
        name='report_detail',
    ),
    # Member Specific Views
    path(
        'member/<slug:member>/', 
        views.MemberPostView.as_view(),
        name='member_posts',
    ),
    path(
        'studio/posts/',
        views.PostStudioListView.as_view(),
        name='post_studio_list',
    ),
    path(
        'responses/member/<slug:member>/', 
        views.MemberResponsePostView.as_view(),
        name='member_responses',
    ),
    path(
        'studio/responses/',
        views.ResponsePostStudioListView.as_view(),
        name='response_studio_list',
    ),
    path(
        'reports/member/<slug:member>/', 
        views.MemberReportPostView.as_view(),
        name='member_reports',
    ),
    # Create Views
    path(
        'add/post/', 
        views.PostCreateView.as_view(),
        name='post_create',
    ),
    path(
        'add/response/<slug:model>-<int:pk>-<slug:members_only>', 
        views.ResponsePostCreateView.as_view(),
        name='response_post_create',
    ),
    path(
        'add/report/', 
        views.ReportPostCreateView.as_view(),
        name='report_post_create',
    ),
    # Update Views
    path(
        'modify/post/<slug:slug>/', 
        views.PostUpdateView.as_view(),
        name='post_update',
    ),
    path(
        'modify/response/<slug:slug>/', 
        views.ResponsePostUpdateView.as_view(),
        name='response_update',
    ),
    # Delete Views
    path(
        'delete/post/<int:pk>/', 
        views.PostDeleteView.as_view(),
        name='post_delete',
    ),
    path(
        'delete/response/<int:pk>/', 
        views.ResponsePostDeleteView.as_view(),
        name='response_delete',
    ),
    path(
        'delete/report/<int:pk>/', 
        views.ResponsePostDeleteView.as_view(),
        name='report_delete',
    ),
    # Publish Views
    path(
        'publish/post/<int:pk>/', 
        views.publish_post_view,
        name='publish_post',
    ),
    path(
        'publish/response/<int:pk>/', 
        views.publish_responsepost_view,
        name='publish_response',
    ),
    # Marshmallow Views
    path(
        '<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_post_view,
        name='post_marshmallow',
    ),
    path(
        'responses/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_responsepost_view,
        name='response_marshmallow',
    ),
]

home/templates/home/home_app_profile_form_sections.html
<div class="form-field">
  <h4 class="form-label">Landing Page Sections</h4>
  {% if sections %}
    <table class="">
      {% for section in sections %}
        <tr>
          <td>
            <a class="form-label" href="{% url 'home:home_page_section_detail' section.pk %}">{{ section }}</a>
          </td>
          <td>
            {% if section.is_enabled %}
              <span class="badge badge-success">Enabled</span>
            {% else %}
              <span class="badge badge-secondary">Disabled</span>
            {% endif %}
          </td>
          {% if show_home_page_section_add_button %}
            <td>
              <a href="{{ home_page_section_add_button|lookup:"url" }}?next={{ request.path }}{% if sections %}&order={{ section.next_order }}{% else %}&order=0{% endif %}">
                <button type="button" class="btn btn-sm btn-primary create-button">+</button>
              </a>
            </td>
          {% endif %}
          {% if show_home_page_section_edit_button %}
            <td>
              <a href="{% url 'home:home_page_section_update' section.pk %}?next={{ request.path }}">
                <button type="button" class="btn btn-sm btn-warning edit-button">&#9998;</button>
              </a>
            </td>
          {% endif %}
          {% if show_home_page_section_edit_button %}
            <td>
              <a href="{% url 'home:home_page_section_delete' section.pk %}?next={{ request.path }}">
                <button type="button" class="btn btn-sm btn-danger delete-button">X</button>
              </a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
  {% else %}
    {% include './homepagesection_add_button.html' %}
  {% endif %}
</div>

home/templates/home/home_app_profile_form_settings.html
{% if show_home_app_profile_settings_edit_button %}
  <div class="form-field">
    <div class="row">
      <div class="col-sm">
        <h4 class="form-label">Profile Settings</h4>
        <p>Change what appears on your homepage</p>
      </div>
      <div class="col-">
        <div class="container">
          {% with home_app_profile_settings_edit_button as button %}
            {% with button|lookup:"url" as button_url and button|lookup:"text" as button_text %}
              {% include 'edit_button.html' %}
            {% endwith %}
          {% endwith %}
        </div>
      </div>
    </div>
  </div>
{% endif %}

home/templates/home/home_form.html
{% extends 'form.html' %}
{% block header_block %}
{% include './home_form_header.html' %}
{% endblock %}

home/templates/home/home_page.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<div class="container-fluid">
  <!-- Heading -->
  {% include './home_page_header.html' %}
  {% if sections or new_posts or new_responses or new_articles or new_stories or new_documents or new_visuals or new_galleries or new_tracks or new_albums or top_posts or top_responses or top_articles or top_stories or top_documents or top_visuals or top_galleries or top_tracks or top_albums or profile.links.count.all > 0 or profile.bitcoin_wallet or profile.litecoin_wallet %}
    <div class="row">
      {% if sections %}
        <div class="col-sm">
          {% if profile.text %}
            <p class="home-page-span">{{ profile.text }}</p>
          {% endif %}
          {% include './home_page_tags.html' %}
	      {% if sections %}
            {% for section in sections %}
              {% include './home_page_section.html' %}
            {% endfor %}
          {% endif %}
          {% if profile.links or profile.bitcoin_wallet or profile.litecoin_wallet %}
            {% include './home_page_links.html' %}
          {% endif %}
        </div>
      {% endif %}
      {% if members or contributors or new_posts or new_responses or new_articles or new_stories or new_documents or new_visuals  or new_galleries or new_tracks or new_albums or top_posts or top_responses or top_articles or top_stories or top_documents or top_visuals or top_galleries or top_tracks or top_albums %}
        <div class="col-sm">
          {% if not sections and profile.text %}
            <p class="home-page-span">{{ profile.text }}</p>
          {% endif %}
          {% if not sections %}
            {% include './home_page_tags.html' %}
          {% endif %}
          {% include './home_page_items.html' %}
          {% if not sections %}
            {% include './home_page_links.html' %}
          {% endif %}
        </div>
      {% elif profile.links or profile.bitcoin_wallet or profile.litecoin_wallet %}
        {% if not sections %}
          <div class="col-sm">
            {% include './home_page_tags.html' %}
            {% include './home_page_links.html' %}
          </div>
        {% endif %}
      {% endif %}
    </div>
  {% elif profile.text %}
    <p class="home-page-span">{{ profile.text }}</p>
  {% else %}
    <span class="home-page-span home-alert"><i>Coming Soon...</i></span>
    <br><br>
  {% endif %}
</div>
{% endblock %}

home/templates/home/home_page_album_item.html
<li class="list-group-item music-list-li">
  <div class="row">
    <div class="col-">
      {% if album.cover %}
        <div class="music-album-list-image" style="background-image:url('{{ album.cover.thumbnail_file.url }}')"></div>
      {% elif album.owner.profile.image %}
        <div class="music-album-list-image" style="background-image:url('{{ album.owner.profile.image.thumbnail_file.url }}')"></div>
      {% else %}
        <div class="music-album-list-image" style="background-image:url('/static/icon.webp')"></div>
      {% endif %}
    </div>
    <div class="col-sm">
      <h5 class="music-title">
        <a href="{% url 'music:album_detail' album.slug %}">
          {{ album.title }}
        </a>
      </h5>
        <p>
        Released by <a href="{% url 'members:member_profile' album.owner.username %}"><span class="index-heading-span">{{ album.owner }}</span></a> on <span class="index-heading-span">{{ album.creation_date|date:"M d, Y" }}</span>
        </p>
    </div>
  </div>
</li>

home/templates/home/home_page_header.html
{% extends 'header.html' %}
{% block logo_block %}
  <img class="home-logo" src="{{ profile.logo.thumbnail_file.url }}" alt="{{ profile.logo.title }}">
{% endblock %}
{% if meta_title and profile.show_title %}
  {% block title_block %}
    <h3 class="home-brand-title home-page-span home-alert">{{ meta_title }}</h3><br>
  {% endblock %}
{% endif %}
{% if meta_desc and profile.show_desc %}
  {% block desc_block %}
    <p class="home-page-span home-alert"><i>{{ meta_desc }}</i></p><br>
  {% endblock %}
{% endif %}
{% block nav_block %}
  {% include './home_page_navbar.html' %}
{% endblock %}
{% block buttons_block %}
  {% if show_site_profile_edit_button %} 
    {% with site_profile_edit_button as button %}
      {% with button|lookup:"url" as button_url and button|lookup:"text" as button_text %}
        {% include 'buttons/edit_button.html' %}
      {% endwith %}
    {% endwith %}
  {% endif %}
  {% if show_profile_edit_button %} 
    {% with profile_edit_button as button %}
      {% with button|lookup:"url" as button_url and button|lookup:"text" as button_text %}
        {% include 'buttons/edit_button.html' %}
      {% endwith %}
    {% endwith %}
  {% endif %}
{% endblock %}

home/templates/home/home_page_navbar.html
<p class="home-page-span home-alert">
  {% if nav_show_posts %}
    <a href="{% url 'posts:posts_page' %}">{{ profile.nav_posts_name }}</a>
  {% endif %}
  {% if nav_show_documentation %}
  | <a href="{% url 'documentation:documentation_page' %}">{{ profile.nav_documentation_name }}</a>
  {% endif %}
  {% if nav_show_art %}
  | <a href="{% url 'art:art_page' %}">{{ profile.nav_art_name }}</a>
  {% endif %}
  {% if nav_show_music %}
  | <a href="{% url 'music:music_page' %}">{{ profile.nav_music_name }}</a>
  {% endif %}
  {% if nav_show_members %}
  | <a href="{% url 'members:members_page' %}">{{ profile.nav_members_name }}</a>
  {% endif %}
</p>

home/templates/home/homeappprofile_form_sections.html
<h4 class="form-label">Landing Page Sections</h4>
{% if sections %}
  <table class="">
    {% for section in sections %}
      <tr>
        <td>
          <a class="form-label" href="{% url 'home:home_page_section_detail' section.pk %}">{{ section }}</a>
        </td>
        <td>
          {% if section.is_enabled %}
            <span class="badge bg-success">Enabled</span>
          {% else %}
            <span class="badge bg-secondary">Disabled</span>
          {% endif %}
          {% with section as object %}
            {% include 'objects/members_only.html' %}
          {% endwith %}
        </td>
        {% if show_home_page_section_add_button %}
          <td>
            <a href="{{ home_page_section_add_button|lookup:"url" }}{% if sections %}?order={{ section.next_order }}{% else %}?order=0{% endif %}">
              <button type="button" class="btn btn-sm btn-primary create-button">+</button>
            </a>
          </td>
        {% endif %}
        {% if show_home_page_section_edit_button %}
          <td>
            <a href="{% url 'home:home_page_section_update' section.pk %}">
              <button type="button" class="btn btn-sm btn-warning edit-button">&#9998;</button>
            </a>
          </td>
        {% endif %}
        {% if show_home_page_section_edit_button %}
          <td>
            <a href="{% url 'home:home_page_section_delete' section.pk %}">
              <button type="button" class="btn btn-sm btn-danger delete-button">X</button>
            </a>
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </table>
{% else %}
  {% if show_home_page_section_add_button %}
    <p>
      <a href="{{ home_page_section_add_button|lookup:"url" }}">
        <button type="button" class="btn btn-sm btn-primary create-button">+</button>
      </a>
    </p>
  {% endif %}
{% endif %}

home/templates/home/post_item.html
<div class="row">
  <div class="col-">
    {% if post.image %}
      <div class="posts-list-image" style="background-image:url('{{ post.image.thumbnail_file.url }}')"></div>
    {% elif post.owner.profile.image %}
      <div class="posts-list-image" style="background-image:url('{{ post.owner.profile.image.thumbnail_file.url }}')"></div>
    {% else %}
      <div class="posts-list-image" style="background-image:url('/static/icon.webp')"></div>
    {% endif %}
  </div>
  <div class="col-sm">
    <h6 class="posts-title">
      <strong><a href="{% url 'posts:post_detail' post.slug %}">
        {{ post.title }}
      </a></strong>
    </h6>
    <p>
      Posted by <a href="{% url 'members:member_profile' post.owner.username %}"><span class="index-heading-span">{{ post.owner }}</span></a> on <span class="index-heading-span">{{ post.creation_date|date:"M d, Y" }}</span>
    </p>
  </div>
</div>
<p>
  {{ post.meta_description }}
</p>
{% if not post.is_public %}
  <span class="badge badge-dark">Unpublished</span>
{% endif %}
{% if post.members_only %}
  <span class="badge badge-warning">Members Only</span>
{% endif %}
{% if post.tags.all.count > 0 %}
  {% with post as object %}
    {% include 'object_tags.html' %}
  {% endwith %}
{% endif %}

home/templates/home/response_item.html
<div class="row">
  <div class="col-">
    {% if response.owner.profile.image %}
      <div class="posts-list-image" style="background-image:url('{{ response.owner.profile.image.thumbnail_file.url }}')"></div>
    {% else %}
      <div class="posts-list-image" style="background-image:url('/static/icon.webp')"></div>
    {% endif %}
  </div>
  <div class="col-sm">
    <h6 class="posts-title">
      <strong><a href="{% url 'posts:response_detail' response.slug %}">
        {{ response.title }}
      </a></strong>
    </h6>
    <p>
      {% include './re_links.html' %}
      Posted by <a href="{% url 'members:member_profile' response.owner.username %}"><span class="index-heading-span">{{ response.owner }}</span></a> on <span class="index-heading-span">{{ response.creation_date|date:"M d, Y" }}</span>
    </p>
  </div>
</div>
<p>
  {{ response.text|truncatechars:155 }}
</p>
{% if not response.is_public %}
  <span class="badge badge-dark">Unpublished</span>
{% endif %}
{% if response.members_only %}
  <span class="badge badge-warning">Members Only</span>
{% endif %}
{% if response.tags.all.count > 0 %}
  {% with response as object %}
    {% include 'object_tags.html' %}
  {% endwith %}
{% endif %}