art/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import art.views as views

app_name = 'art'

urlpatterns = [
    # Music front page
    path(
        '',
        views.ArtPageView.as_view(),
        name="art_page",
    ),
    # Art app profile
    ## Update
    path(
        'profile/update/<int:pk>/', 
        views.ArtAppProfileUpdateView.as_view(),
        name='art_app_profile_update',
    ),
    # Art landing page section views
    ## Create
    path(
        'add/section/', 
        views.ArtPageSectionCreateView.as_view(),
        name='art_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/', 
        views.ArtPageSectionDetailView.as_view(),
        name='art_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.ArtPageSectionUpdateView.as_view(),
        name='art_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/', 
        views.ArtPageSectionDeleteView.as_view(),
        name='art_page_section_delete',
    ),
    # Read Views
    path(
        'galleries/new/',
        views.GalleryListView.as_view(),
        name='new_galleries',
    ),
    path(
        'galleries/',
        views.TopGalleryListView.as_view(),
        name='top_galleries',
    ),
    path(
        'galleries/<slug:slug>/',
        views.GalleryDetailView.as_view(),
        name='gallery_detail',
    ),
    path(
        'visuals/new/',
        views.VisualListView.as_view(),
        name='new_visuals',
    ),
    path(
        'visuals/',
        views.TopVisualListView.as_view(),
        name='top_visuals',
    ),
    path(
        'visuals/<slug:slug>/',
        views.VisualDetailView.as_view(),
        name='visual_detail',
    ),
    path(
        'member/<slug:member>/galleries/',
        views.MemberGalleryView.as_view(),
        name='member_galleries',
    ),
    path(
        'studio/galleries/',
        views.GalleryStudioListView.as_view(),
        name='gallery_studio_list',
    ),
    path(
        'member/<slug:member>/visuals/',
        views.MemberVisualView.as_view(),
        name='member_visuals',
    ),
    path(
        'studio/articles/',
        views.VisualStudioListView.as_view(),
        name='visual_studio_list',
    ),
    # Create Views
    path(
        'add/gallery/',
        views.GalleryCreateView.as_view(),
        name='gallery_create',
    ),
    path(
        'add/visual/',
        views.VisualCreateView.as_view(),
        name='visual_create',
    ),
    # Update Views
    path(
        'modify/gallery/<slug:slug>/',
        views.GalleryUpdateView.as_view(),
        name='gallery_update',
    ),
    path(
        'modify/visual/<slug:slug>/',
        views.VisualUpdateView.as_view(),
        name='visual_update',
    ),
    # Delete Views
    path(
        'delete/gallery/<int:pk>/',
        views.GalleryDeleteView.as_view(),
        name='gallery_delete',
    ),
    path(
        'delete/visual/<int:pk>/',
        views.VisualDeleteView.as_view(),
        name='visual_delete',
    ),
    # Publish Views
    path(
        'publish/gallery/<int:pk>/',
        views.publish_gallery_view,
        name='publish_gallery',
    ),
    path(
        'publish/visual/<int:pk>/',
        views.publish_visual_view,
        name='publish_visual',
    ),
    # Marshmallow Views
    path(
        'galleries/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_gallery_view,
        name='gallery_marshmallow',
    ),
    path(
        'visuals/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_visual_view,
        name='visual_marshmallow',
    ),
]

crypto/urls.py
from django.urls import path
import crypto.views as views

app_name= "crypto"

urlpatterns = [
    # Read Views
    path(
        'wallets/bitcoin/',
        views.BitcoinWalletListView.as_view(),
        name='bitcoinwallets',
    ),
    path(
        'wallets/litecoin/',
        views.LitecoinWalletListView.as_view(),
        name='litecoinwallets',
    ),
    path(
        'wallets/bitcoin/<int:pk>/',
        views.BitcoinWalletDetailView.as_view(),
        name='bitcoinwallet_detail',
    ),
    path(
        'wallets/litecoin/<int:pk>/',
        views.LitecoinWalletDetailView.as_view(),
        name='litecoinwallet_detail',
    ),
    # Member Specific Views
    path(
        'member/<slug:member>/donations/bitcoin/',
        views.MemberBitcoinWalletView.as_view(),
        name='member_bitcoinwallets',
    ),
    path(
        'member/<slug:member>/donations/litecoin/',
        views.MemberLitecoinWalletView.as_view(),
        name='member_litecoinwallets',
    ),
    # Create VIews
    path(
        'add/bitcoin-wallet/',
        views.BitcoinWalletCreateView.as_view(),
        name='bitcoinwallet_create',
    ),
    path(
        'add/litecoin-wallet/',
        views.LitecoinWalletCreateView.as_view(),
        name='litecoinwallet_create',
    ),
    # Update Views
    path(
        'modify/bitcoin-wallet/<int:pk>/',
        views.BitcoinWalletUpdateView.as_view(),
        name='bitcoinwallet_update',
    ),
    path(
        'modify/litecoin-wallet/<int:pk>/',
        views.LitecoinWalletUpdateView.as_view(),
        name='litecoinwallet_update',
    ),
    # Delete Views
    path(
        'delete/bitcoin-wallet/<int:pk>/',
        views.BitcoinWalletDeleteView.as_view(),
        name='bitcoinwallet_delete',
    ),
    path(
        'delete/litecoin-wallet/<int:pk>/',
        views.LitecoinWalletDeleteView.as_view(),
        name='litecoinwallet_delete',
    ),

]

objects/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import objects.views as views  

app_name = 'objects'

urlpatterns = [
    # Landing page
    path('', views.ObjectsPageView.as_view(), name='objects_page'),

    # Home app profile
    ## Update
    path(
        'profile/update/<int:pk>/transcoder/settings/', 
        views.ObjectsAppTranscoderSettingsUpdateView.as_view(),
        name='objects_app_transcoder_settings_update',
    ),
    path(
        'profile/update/<int:pk>/', 
        views.ObjectsAppProfileUpdateView.as_view(),
        name='objects_app_profile_update',
    ),
    # Home landing page section views
    ## Create
    path(
        'add/section/', 
        views.ObjectsPageSectionCreateView.as_view(),
        name='objects_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.ObjectsPageSectionDetailView.as_view(),
        name='objects_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.ObjectsPageSectionUpdateView.as_view(),
        name='objects_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.ObjectsPageSectionDeleteView.as_view(),
        name='objects_page_section_delete',
    ),

    # Multimedia objects
    ## Read views
    path(
        'images/',
        views.ImageListView.as_view(),
        name='public_images',
    ),
    path(
        'images/<int:pk>/',
        views.ImageDetailView.as_view(),
        name='image_detail',
    ),
    path(
        'sounds/',
        views.SoundListView.as_view(),
        name='public_sounds',
    ),
    path(
        'sounds/<int:pk>/',
        views.SoundDetailView.as_view(),
        name='sound_detail',
    ),
    path(
        'videos/',
        views.VideoListView.as_view(),
        name='public_videos',
    ),
    path(
        'videos/<int:pk>/',
        views.VideoDetailView.as_view(),
        name='video_detail',
    ),
    path(
        'code/',
        views.CodeListView.as_view(),
        name='public_code',
    ),
    path(
        'code/<int:pk>/',
        views.CodeDetailView.as_view(),
        name='code_detail',
    ),
    path(
        'links/',
        views.LinkListView.as_view(),
        name='public_links',
    ),
    path(
        'links/<int:pk>/',
        views.LinkDetailView.as_view(),
        name='link_detail',
    ),
    path(
        'tags/',
        views.TagListView.as_view(),
        name='tags',
    ),
    path(
        'tags/<slug:slug>/',
        views.TagDetailView.as_view(),
        name='tag_detail',
    ),
    path(
        'tags/get-tag-detail',
        views.get_tag_detail,
        name='get_tag_detail',
    ),
    # Member Specific Views
    path(
        'member/<slug:member>/images/',
        views.MemberImageView.as_view(),
        name='member_images',
    ),
    path(
        'studio/images/',
        views.ImageStudioListView.as_view(),
        name='image_studio_list',
    ),
    path(
        'member/<slug:member>/sounds/',
        views.MemberSoundView.as_view(),
        name='member_sounds',
    ),
    path(
        'studio/sounds/',
        views.SoundStudioListView.as_view(),
        name='sound_studio_list',
    ),
    path(
        'member/<slug:member>/videos/',
        views.MemberVideoView.as_view(),
        name='member_videos',
    ),
    path(
        'studio/videos/',
        views.VideoStudioListView.as_view(),
        name='video_studio_list',
    ),
    path(
        'member/<slug:member>/code/',
        views.MemberCodeView.as_view(),
        name='member_code',
    ),
    path(
        'studio/code/',
        views.CodeStudioListView.as_view(),
        name='code_studio_list',
    ),
    path(
        'member/<slug:member>/links/',
        views.MemberLinkView.as_view(),
        name='member_links',
    ),
    path(
        'studio/links/',
        views.LinkStudioListView.as_view(),
        name='link_studio_list',
    ),
    # Create Views
    path(
        'add/image/',
        views.ImageCreateView.as_view(),
        name='image_create',
    ),
    path(
        'add/sound/',
        views.SoundCreateView.as_view(),
        name='sound_create',
    ),
    path(
        'add/video/',
        views.VideoCreateView.as_view(),
        name='video_create',
    ),
    path(
        'add/code/',
        views.CodeCreateView.as_view(),
        name='code_create',
    ),
    path(
        'add/link/',
        views.LinkCreateView.as_view(),
        name='link_create',
    ),
    path(
        'add/tag/',
        views.TagCreateView.as_view(),
        name='tag_create',
    ),
    # Update Views
    path(
        'modify/image/<int:pk>',
        views.ImageUpdateView.as_view(),
        name='image_update',
    ),
    path(
        'modify/sound/<int:pk>',
        views.SoundUpdateView.as_view(),
        name='sound_update',
    ),
    path(
        'modify/video/<int:pk>',
        views.VideoUpdateView.as_view(),
        name='video_update',
    ),
    path(
        'modify/code/<int:pk>',
        views.CodeUpdateView.as_view(),
        name='code_update',
    ),
    path(
        'modify/link/<int:pk>',
        views.LinkUpdateView.as_view(),
        name='link_update',
    ),
    path(
        'modify/tag/<slug:slug>',
        views.TagUpdateView.as_view(),
        name='tag_update',
    ),
    # Delete Views
    path(
        'delete/image/<int:pk>',
        views.ImageDeleteView.as_view(),
        name='image_delete',
    ),
    path(
        'delete/sound/<int:pk>',
        views.SoundDeleteView.as_view(),
        name='sound_delete',
    ),
    path(
        'delete/video/<int:pk>',
        views.VideoDeleteView.as_view(),
        name='video_delete',
    ),
    path(
        'delete/code/<int:pk>',
        views.CodeDeleteView.as_view(),
        name='code_delete',
    ),
    path(
        'delete/link/<int:pk>',
        views.LinkDeleteView.as_view(),
        name='link_delete',
    ),
    path(
        'delete/tag/<slug:slug>',
        views.TagDeleteView.as_view(),
        name='tag_delete',
    ),
    # Publish Views
    path(
        'publish/image/<int:pk>',
        views.publish_image_view,
        name='publish_image',
    ),
    path(
        'publish/sound/<int:pk>',
        views.publish_sound_view,
        name='publish_sound',
    ),
    path(
        'publish/video/<int:pk>',
        views.publish_video_view,
        name='publish_video',
    ),
    path(
        'publish/code/<int:pk>',
        views.publish_code_view,
        name='publish_code',
    ),
    path(
        'publish/link/<int:pk>',
        views.publish_link_view,
        name='publish_link',
    ),
    # Tag Views
    path(
        'tags/galleries/<slug:slug>',
        views.GalleryByTag.as_view(),
        name='gallery_tag',
    ),
    path(
        'tags/visuals/<slug:slug>',
        views.VisualByTag.as_view(),
        name='visual_tag',
    ),
    path(
        'tags/albums/<slug:slug>',
        views.AlbumByTag.as_view(),
        name='album_tag',
    ),
    path(
        'tags/tracks/<slug:slug>',
        views.TrackByTag.as_view(),
        name='track_tag',
    ),
    path(
        'tags/stories/<slug:slug>',
        views.StoryByTag.as_view(),
        name='story_tag',
    ),
    path(
        'tags/posts/<slug:slug>',
        views.PostByTag.as_view(),
        name='post_tag',
    ),
    path(
        'tags/articles/<slug:slug>',
        views.ArticleByTag.as_view(),
        name='article_tag',
    ),
    path(
        'tags/support-documents/<slug:slug>',
        views.SupportDocumentByTag.as_view(),
        name='support_document_tag',
    ),
    path(
        'tags/images/<slug:slug>',
        views.ImageByTag.as_view(),
        name='image_tag',
    ),
    path(
        'tags/sounds/<slug:slug>',
        views.SoundByTag.as_view(),
        name='sound_tag',
    ),
    path(
        'tags/videos/<slug:slug>',
        views.VideoByTag.as_view(),
        name='video_tag',
    ),
    path(
        'tags/code/<slug:slug>',
        views.CodeByTag.as_view(),
        name='code_tag',
    ),
    path(
        'tags/links/<slug:slug>',
        views.LinkByTag.as_view(),
        name='link_tag',
    ),
    # Marshmallow Views
    path(
        'images/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_image_view,
        name='image_marshmallow',
    ),
    path(
        'sounds/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_sound_view,
        name='sound_marshmallow',
    ),
    path(
        'videos/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_video_view,
        name='video_marshmallow',
    ),
    path(
        'code/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_code_view,
        name='code_marshmallow',
    ),
    path(
        'links/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_link_view,
        name='link_marshmallow',
    ),
    path(
        'tags/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_tag_view,
        name='tag_marshmallow',
    ),
]

templates/objects/members_only.html
{% if object.members_only %}
  <span class="badge bg-warning">Members Only</span>
{% endif %}

templates/objects/object_code.html
{% if code.file_path %}
  <span class="code-block"><strong>{{ code.file_path }}</strong></span><br>
{% endif %}
{% load custom_filters %}
{{ code.code|highlight_syntax:code.file_path|safe }}
<p>
  {% if code.text %}
    {{ code.text }}<br>
  {% endif %}
  {% if code.source and code.source_url %}
    <i>Source: <a href="{{ code.source_url }}">{{ code.source }}</a></i><br>
  {% elif code.source %}
    <i>Source: {{ code.source }}</i>
  {% elif code.source_url %}
    <i>Source: <a href="{{ code.source_url }}">{{ code.source_url }}</a></i><br>
  {% endif %}
  {% if code.owner.pk == request.user.pk %}
    <a href="{% url 'objects:code_update' code.pk %}?next={{ request.path }}">
      <button class="btn btn-sm btn-warning edit-button">&#9998;</button>
    </a>
  {% endif %}
</p>

templates/objects/object_create_buttons.html
{% if perms.objects.add_image %}
  <a class="btn btn-sm btn-primary" href="{% url 'objects:image_create' %}?next={{ request.path }}">+Image</a>
{% endif %}
{% if perms.objects.add_sound %}
  <a class="btn btn-sm btn-primary" href="{% url 'objects:sound_create' %}?next={{ request.path }}">+Sound</a>
{% endif %}
{% if perms.objects.add_video %}
  <a class="btn btn-sm btn-primary" href="{% url 'objects:video_create' %}?next={{ request.path }}">+Video</a>
{% endif %}
{% if perms.objects.add_code %}
  <a class="btn btn-sm btn-primary" href="{% url 'objects:code_create' %}?next={{ request.path }}">+Code</a>
{% endif %}
{% if perms.objects.add_link %}
  <a class="btn btn-sm btn-primary" href="{% url 'objects:link_create' %}?next={{ request.path }}">+Link</a>
{% endif %}
{% if perms.objects.add_tag %}
  <a class="btn btn-sm btn-primary" href="{% url 'objects:tag_create' %}?next={{ request.path }}">+Tag</a>
{% endif %}

templates/objects/object_crypto_wallets.html
<!-- Crypto Wallets -->
<!-- Bitcoin Wallet -->
{% if bitcoin_wallet %}
  <div class="section">
    <div class="row">
      <div class="col-auto">
        <img class="crypto-qr-sm" src="{{ bitcoin_wallet.qr_code_lg.url }}" alt="bitcoin:{{ bitcoin_wallet.public_address }}"><br>
      </div>
      <div class="col">
        {% load static %}
        <h5>
          <img src="{% static 'bitcoin_logo_sm.webp' %}">  Bitcoin Accepted Here
        </h5>
        <p>
          <span class="crypto-address-block">{{ bitcoin_wallet.public_address }}</span>
          {% if request.user == bitcoin_wallet.owner %}
            <a href="{% url 'crypto:bitcoinwallet_update' bitcoin_wallet.pk %}?next={{ request.path }}">
              <button class="btn btn-sm btn-warning edit-button">&#9998;</button>
            </a>
          {% endif %}
        </p>
        {% if bitcoin_wallet.text %}
          <div class="crypto-text-md">
            {{ bitcoin_wallet.text|linebreaks }}
          </div>
        {% endif %}
      </div>
    </div>
    <hr class="crypto-hr">
  </div>
{% endif %}
<!-- Litecoin Wallet -->
{% if litecoin_wallet %}
  <div class="section">
    <div class="row">
      <div class="col-auto">
        <img class="crypto-qr-sm" src="{{ litecoin_wallet.qr_code_lg.url }}" alt="litecoin:{{ litecoin_wallet.public_address }}"><br>
      </div>
      <div class="col">
        {% load static %}
        <h5>
          <img src="{% static 'litecoin_logo_sm.webp' %}">  Litecoin Accepted Here
        </h5>
        <p>
          <span class="crypto-address-block">{{ litecoin_wallet.public_address }}</span>
          {% if request.user == litecoin_wallet.owner %}
            <a href="{% url 'crypto:litecoinwallet_update' litecoin_wallet.pk %}?next={{ request.path }}">
              <button class="btn btn-sm btn-warning edit-button">&#9998;</button>
            </a>
          {% endif %}
        </p>
        {% if litecoin_wallet.text %}
          <div class="crypto-text-md">
            {{ litecoin_wallet.text|linebreaks }}
          </div>
        {% endif %}
      </div>
    </div>
    <hr>
  </div>
{% endif %}

templates/objects/object_image.html
{% if image.text or image.credit %}
  <div class="card border-0 bg-transparent text-center" style="min-width: 250px;">
    <a href="{{ image.image_file.url }}">
      <img class="section-image" src="{{ image.image_file.url }}" alt="{{ image.title }}">
    </a>
    <div class="card-body">
      <div class="row">
        <div class="col-sm">
          <p style="font-size: 0.8em;">
            {% if image.text %}
              {{ image.text }}<br>
            {% endif %}
            {% if image.credit %}
              <i>{{ image.credit }}</i><br>
            {% endif %}
          </p>
        </div>
        {% if image.owner.pk == request.user.pk %}
          <div class="col-auto">
            <a href="{% url 'objects:image_update' image.pk %}?next={{ request.path }}"><button class="btn btn-sm btn-warning edit-button">&#9998;</button></a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  <br>
{% else %}
  <div class="card border-0 bg-transparent text-center" style="min-width: 250px; max-width: 100%;">
    <a href="{{ image.image_file.url }}">
      <img class="section-image" src="{{ image.image_file.url }}" alt="{{ image.title }}">
    </a>
  </div>
  {% if image.owner.pk == request.user.pk %}
    <p><a href="{% url 'objects:image_update' image.pk %}?next={{ request.path }}">
      <button class="btn btn-sm btn-warning edit-button">&#9998;</button>
    </a></p>
  {% endif %}
  <br>
{% endif %}

templates/objects/object_image_text.html
<div class="row">
  {% if text %}
    <div class="col-sm">
      <div class="section-text">
        {{ text|linebreaks }}
      </div>
    </div>
  {% endif %}
  {% if image %}
    <div class="col-sm">
      <a href="{{ image.image_file.url }}">
        <img class="section-image" src="{{ image.image_file.url }}" alt="{{ image.title }}">
      </a><br><br>
      <span class="">
        {% if image.text %}
          {{ image.text }}<br>
        {% endif %}
        {% if image.credit %}
          <i>{{ image.credit }}</i><br>
        {% endif %}
        {% if image.owner == request.user %}
          <a href="{% url 'objects:image_update' image.pk %}?next={{ request.path }}">
            <button class="btn btn-sm btn-warning edit-button">&#9998;</button>
          </a>
        {% endif %}
      </span>
    </div>
  {% endif %}
</div>

templates/objects/object_links.html
{% for link in links %}
  <p>
    {% include 'objects/object_link.html' %}
  </p>
{% endfor %}

templates/objects/object_meta_data.html
{% if object.is_public %}
  <p>
    Contributed by <a href="{% url 'members:member_profile' object.owner.profile.slug %}">{{ object.owner }}</a> on {{ object.publication_date }}
    {% if object.last_modified > object.publication_date %}
      <br>Last updated on {{ object.last_modified }}
    {% endif %}
  </p>
{% else %}
  <p>
    Created by <a href="{% url 'members:member_profile' object.owner.profile.slug %}">{{ object.owner }}</a> on {{ object.creation_date }}
  </p>
  {% endif %}

templates/objects/object_sound.html
<audio controls="controls" preload="none">
  {% include 'audio_mime_types.html' %}
</audio>
<p>
  {% if sound.text %}
    {{ sound.text }}
    <br>
  {% endif %}
  {% if sound.credit %}
    <i>{{ sound.credit }}</i><br>
  {% endif %}
  {% if sound.owner.pk == request.user.pk %}
    <a href="{% url 'objects:sound_update' sound.pk %}?next={{ request.path }}">
      <button class="btn btn-sm btn-warning edit-button">&#9998;</button>
    </a>
  {% endif %}
</p>

templates/objects/object_tags.html
{% for tag in object.tags.all %}<a href="{% url 'objects:tag_detail' tag.slug %}"><span class="badge bg-secondary">{{ tag }}</span></a> {% endfor %}<br>

templates/objects/object_video.html
<video class="section-video" preload="none" controls="controls">
  {% include 'video_mime_types.html' %}
</video>
<br>
<p>
  {% if video.text %}
    {{ video.text }}<br>
  {% endif %}
  {% if video.credit %}
    <i>{{ video.credit }}</i><br>
  {% endif %}
  {% if video.owner.pk == request.user.pk %}
    <a href="{% url 'objects:video_update' video.pk %}?next={{ request.path }}">
      <button class="btn btn-sm btn-warning edit-button">&#9998;</button>
    </a>
  {% endif %}
</p>

templates/objects/objects_table.html
<div style="overflow-x:auto;">
  {% if object_list.all.count > 0 %}
    <table class="studio-list-table">
      <tr>
        <th class="studio-list-table">Title</th>
        <th class="studio-list-table">Status</th>
        <th class="studio-list-table">Last Modified</th>
        <th class="studio-list-table">Uploaded</th>
      </tr>
      {% for object in object_list %}
        <tr class="studio-list-table">
          <td class="studio-list-table">
            <a href="{{ object.get_absolute_url }}">
              {% if object.title %}
                {{ object.title|truncatechars:64 }}
              {% else %}
                Untitled
              {% endif %}
            </a>
          </td>
          <td class="studio-list-table">
            {% include 'objects/unpublished.html' %}
            {% include 'objects/published.html' %}
          </td>
          <td class="studio-list-table">{{ object.last_modified|date:"M d, Y" }}</td>
          <td class="studio-list-table">{{ object.creation_date|date:"M d, Y" }}</td>
        </tr>
      {% endfor %}
    </table>
    <br>
  {% else %}
    <p class="objects-section">There are no items to show yet.</p>
  {% endif %}
</div>

templates/objects/published.html
{% if object.is_public %}
  <span class="badge bg-success">Published</span>
{% endif %}

templates/objects/unpublished.html
{% if not object.is_public %}
  <span class="badge bg-dark">Unpublished</span>
{% endif %}