art/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import art.views as views

app_name = 'art'

urlpatterns = [
    # Music front page
    path(
        '',
        views.ArtPageView.as_view(),
        name="art_page",
    ),
    # Art app profile
    ## Update
    path(
        'profile/update/<int:pk>/', 
        views.ArtAppProfileUpdateView.as_view(),
        name='art_app_profile_update',
    ),
    # Art landing page section views
    ## Create
    path(
        'add/section/', 
        views.ArtPageSectionCreateView.as_view(),
        name='art_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/', 
        views.ArtPageSectionDetailView.as_view(),
        name='art_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.ArtPageSectionUpdateView.as_view(),
        name='art_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/', 
        views.ArtPageSectionDeleteView.as_view(),
        name='art_page_section_delete',
    ),
    # Read Views
    path(
        'galleries/new/',
        views.GalleryListView.as_view(),
        name='new_galleries',
    ),
    path(
        'galleries/',
        views.TopGalleryListView.as_view(),
        name='top_galleries',
    ),
    path(
        'galleries/<slug:slug>/',
        views.GalleryDetailView.as_view(),
        name='gallery_detail',
    ),
    path(
        'visuals/new/',
        views.VisualListView.as_view(),
        name='new_visuals',
    ),
    path(
        'visuals/',
        views.TopVisualListView.as_view(),
        name='top_visuals',
    ),
    path(
        'visuals/<slug:slug>/',
        views.VisualDetailView.as_view(),
        name='visual_detail',
    ),
    path(
        'member/<slug:member>/galleries/',
        views.MemberGalleryView.as_view(),
        name='member_galleries',
    ),
    path(
        'studio/galleries/',
        views.GalleryStudioListView.as_view(),
        name='gallery_studio_list',
    ),
    path(
        'member/<slug:member>/visuals/',
        views.MemberVisualView.as_view(),
        name='member_visuals',
    ),
    path(
        'studio/articles/',
        views.VisualStudioListView.as_view(),
        name='visual_studio_list',
    ),
    # Create Views
    path(
        'add/gallery/',
        views.GalleryCreateView.as_view(),
        name='gallery_create',
    ),
    path(
        'add/visual/',
        views.VisualCreateView.as_view(),
        name='visual_create',
    ),
    # Update Views
    path(
        'modify/gallery/<slug:slug>/',
        views.GalleryUpdateView.as_view(),
        name='gallery_update',
    ),
    path(
        'modify/visual/<slug:slug>/',
        views.VisualUpdateView.as_view(),
        name='visual_update',
    ),
    # Delete Views
    path(
        'delete/gallery/<int:pk>/',
        views.GalleryDeleteView.as_view(),
        name='gallery_delete',
    ),
    path(
        'delete/visual/<int:pk>/',
        views.VisualDeleteView.as_view(),
        name='visual_delete',
    ),
    # Publish Views
    path(
        'publish/gallery/<int:pk>/',
        views.publish_gallery_view,
        name='publish_gallery',
    ),
    path(
        'publish/visual/<int:pk>/',
        views.publish_visual_view,
        name='publish_visual',
    ),
    # Marshmallow Views
    path(
        'galleries/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_gallery_view,
        name='gallery_marshmallow',
    ),
    path(
        'visuals/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_visual_view,
        name='visual_marshmallow',
    ),
]

objects/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import objects.views as views  

app_name = 'objects'

urlpatterns = [
    # Landing page
    path('', views.ObjectsPageView.as_view(), name='objects_page'),

    # Home app profile
    ## Update
    path(
        'profile/update/<int:pk>/transcoder/settings/', 
        views.ObjectsAppTranscoderSettingsUpdateView.as_view(),
        name='objects_app_transcoder_settings_update',
    ),
    path(
        'profile/update/<int:pk>/', 
        views.ObjectsAppProfileUpdateView.as_view(),
        name='objects_app_profile_update',
    ),
    # Home landing page section views
    ## Create
    path(
        'add/section/', 
        views.ObjectsPageSectionCreateView.as_view(),
        name='objects_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.ObjectsPageSectionDetailView.as_view(),
        name='objects_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.ObjectsPageSectionUpdateView.as_view(),
        name='objects_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.ObjectsPageSectionDeleteView.as_view(),
        name='objects_page_section_delete',
    ),

    # Multimedia objects
    ## Read views
    path(
        'images/',
        views.ImageListView.as_view(),
        name='public_images',
    ),
    path(
        'images/<int:pk>/',
        views.ImageDetailView.as_view(),
        name='image_detail',
    ),
    path(
        'sounds/',
        views.SoundListView.as_view(),
        name='public_sounds',
    ),
    path(
        'sounds/<int:pk>/',
        views.SoundDetailView.as_view(),
        name='sound_detail',
    ),
    path(
        'videos/',
        views.VideoListView.as_view(),
        name='public_videos',
    ),
    path(
        'videos/<int:pk>/',
        views.VideoDetailView.as_view(),
        name='video_detail',
    ),
    path(
        'code/',
        views.CodeListView.as_view(),
        name='public_code',
    ),
    path(
        'code/<int:pk>/',
        views.CodeDetailView.as_view(),
        name='code_detail',
    ),
    path(
        'links/',
        views.LinkListView.as_view(),
        name='public_links',
    ),
    path(
        'links/<int:pk>/',
        views.LinkDetailView.as_view(),
        name='link_detail',
    ),
    path(
        'tags/',
        views.TagListView.as_view(),
        name='tags',
    ),
    path(
        'tags/<slug:slug>/',
        views.TagDetailView.as_view(),
        name='tag_detail',
    ),
    path(
        'tags/get-tag-detail',
        views.get_tag_detail,
        name='get_tag_detail',
    ),
    # Member Specific Views
    path(
        'member/<slug:member>/images/',
        views.MemberImageView.as_view(),
        name='member_images',
    ),
    path(
        'studio/images/',
        views.ImageStudioListView.as_view(),
        name='image_studio_list',
    ),
    path(
        'member/<slug:member>/sounds/',
        views.MemberSoundView.as_view(),
        name='member_sounds',
    ),
    path(
        'studio/sounds/',
        views.SoundStudioListView.as_view(),
        name='sound_studio_list',
    ),
    path(
        'member/<slug:member>/videos/',
        views.MemberVideoView.as_view(),
        name='member_videos',
    ),
    path(
        'studio/videos/',
        views.VideoStudioListView.as_view(),
        name='video_studio_list',
    ),
    path(
        'member/<slug:member>/code/',
        views.MemberCodeView.as_view(),
        name='member_code',
    ),
    path(
        'studio/code/',
        views.CodeStudioListView.as_view(),
        name='code_studio_list',
    ),
    path(
        'member/<slug:member>/links/',
        views.MemberLinkView.as_view(),
        name='member_links',
    ),
    path(
        'studio/links/',
        views.LinkStudioListView.as_view(),
        name='link_studio_list',
    ),
    # Create Views
    path(
        'add/image/',
        views.ImageCreateView.as_view(),
        name='image_create',
    ),
    path(
        'add/sound/',
        views.SoundCreateView.as_view(),
        name='sound_create',
    ),
    path(
        'add/video/',
        views.VideoCreateView.as_view(),
        name='video_create',
    ),
    path(
        'add/code/',
        views.CodeCreateView.as_view(),
        name='code_create',
    ),
    path(
        'add/link/',
        views.LinkCreateView.as_view(),
        name='link_create',
    ),
    path(
        'add/tag/',
        views.TagCreateView.as_view(),
        name='tag_create',
    ),
    # Update Views
    path(
        'modify/image/<int:pk>',
        views.ImageUpdateView.as_view(),
        name='image_update',
    ),
    path(
        'modify/sound/<int:pk>',
        views.SoundUpdateView.as_view(),
        name='sound_update',
    ),
    path(
        'modify/video/<int:pk>',
        views.VideoUpdateView.as_view(),
        name='video_update',
    ),
    path(
        'modify/code/<int:pk>',
        views.CodeUpdateView.as_view(),
        name='code_update',
    ),
    path(
        'modify/link/<int:pk>',
        views.LinkUpdateView.as_view(),
        name='link_update',
    ),
    path(
        'modify/tag/<slug:slug>',
        views.TagUpdateView.as_view(),
        name='tag_update',
    ),
    # Delete Views
    path(
        'delete/image/<int:pk>',
        views.ImageDeleteView.as_view(),
        name='image_delete',
    ),
    path(
        'delete/sound/<int:pk>',
        views.SoundDeleteView.as_view(),
        name='sound_delete',
    ),
    path(
        'delete/video/<int:pk>',
        views.VideoDeleteView.as_view(),
        name='video_delete',
    ),
    path(
        'delete/code/<int:pk>',
        views.CodeDeleteView.as_view(),
        name='code_delete',
    ),
    path(
        'delete/link/<int:pk>',
        views.LinkDeleteView.as_view(),
        name='link_delete',
    ),
    path(
        'delete/tag/<slug:slug>',
        views.TagDeleteView.as_view(),
        name='tag_delete',
    ),
    # Publish Views
    path(
        'publish/image/<int:pk>',
        views.publish_image_view,
        name='publish_image',
    ),
    path(
        'publish/sound/<int:pk>',
        views.publish_sound_view,
        name='publish_sound',
    ),
    path(
        'publish/video/<int:pk>',
        views.publish_video_view,
        name='publish_video',
    ),
    path(
        'publish/code/<int:pk>',
        views.publish_code_view,
        name='publish_code',
    ),
    path(
        'publish/link/<int:pk>',
        views.publish_link_view,
        name='publish_link',
    ),
    # Tag Views
    path(
        'tags/galleries/<slug:slug>',
        views.GalleryByTag.as_view(),
        name='gallery_tag',
    ),
    path(
        'tags/visuals/<slug:slug>',
        views.VisualByTag.as_view(),
        name='visual_tag',
    ),
    path(
        'tags/albums/<slug:slug>',
        views.AlbumByTag.as_view(),
        name='album_tag',
    ),
    path(
        'tags/tracks/<slug:slug>',
        views.TrackByTag.as_view(),
        name='track_tag',
    ),
    path(
        'tags/stories/<slug:slug>',
        views.StoryByTag.as_view(),
        name='story_tag',
    ),
    path(
        'tags/posts/<slug:slug>',
        views.PostByTag.as_view(),
        name='post_tag',
    ),
    path(
        'tags/articles/<slug:slug>',
        views.ArticleByTag.as_view(),
        name='article_tag',
    ),
    path(
        'tags/support-documents/<slug:slug>',
        views.SupportDocumentByTag.as_view(),
        name='support_document_tag',
    ),
    path(
        'tags/images/<slug:slug>',
        views.ImageByTag.as_view(),
        name='image_tag',
    ),
    path(
        'tags/sounds/<slug:slug>',
        views.SoundByTag.as_view(),
        name='sound_tag',
    ),
    path(
        'tags/videos/<slug:slug>',
        views.VideoByTag.as_view(),
        name='video_tag',
    ),
    path(
        'tags/code/<slug:slug>',
        views.CodeByTag.as_view(),
        name='code_tag',
    ),
    path(
        'tags/links/<slug:slug>',
        views.LinkByTag.as_view(),
        name='link_tag',
    ),
    # Marshmallow Views
    path(
        'images/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_image_view,
        name='image_marshmallow',
    ),
    path(
        'sounds/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_sound_view,
        name='sound_marshmallow',
    ),
    path(
        'videos/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_video_view,
        name='video_marshmallow',
    ),
    path(
        'code/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_code_view,
        name='code_marshmallow',
    ),
    path(
        'links/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_link_view,
        name='link_marshmallow',
    ),
    path(
        'tags/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_tag_view,
        name='tag_marshmallow',
    ),
]

posts/urls.py
from django.urls import path
import posts.views as views

app_name= "posts"

urlpatterns = [
    # Posts landing page
    path(
        '',
        views.PostsPageView.as_view(),
        name="posts_page",
    ),
    # Posts app profile
    ## Update
    path(
        'profile/update/<int:pk>/',
        views.PostsAppProfileUpdateView.as_view(),
        name='posts_app_profile_update',
    ),
    # Posts landing page section views
    ## Create
    path(
        'add/section/',
        views.PostsPageSectionCreateView.as_view(),
        name='posts_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.PostsPageSectionDetailView.as_view(),
        name='posts_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/',
        views.PostsPageSectionUpdateView.as_view(),
        name='posts_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.PostsPageSectionDeleteView.as_view(),
        name='posts_page_section_delete',
    ),
    # Read Views
    path(
        'new/', 
        views.PostListView.as_view(),
        name='public_posts',
    ),
    path(
        'top/', 
        views.TopPostListView.as_view(),
        name='top_posts',
    ),
    path(
        'responses/', 
        views.ResponsePostListView.as_view(),
        name='public_responses',
    ),
    path(
        'responses/top/', 
        views.TopResponsePostListView.as_view(),
        name='top_responses',
    ),
    path(
        'reports/', 
        views.ReportPostListView.as_view(),
        name='reports',
    ),
    path(
        '<slug:slug>/', 
        views.PostDetailView.as_view(),
        name='post_detail',
    ),
    path(
        'responses/<slug:slug>/', 
        views.ResponsePostDetailView.as_view(),
        name='response_detail',
    ),
    path(
        'reports/<int:pk>/', 
        views.ReportPostDetailView.as_view(),
        name='report_detail',
    ),
    # Member Specific Views
    path(
        'member/<slug:member>/', 
        views.MemberPostView.as_view(),
        name='member_posts',
    ),
    path(
        'studio/posts/',
        views.PostStudioListView.as_view(),
        name='post_studio_list',
    ),
    path(
        'responses/member/<slug:member>/', 
        views.MemberResponsePostView.as_view(),
        name='member_responses',
    ),
    path(
        'studio/responses/',
        views.ResponsePostStudioListView.as_view(),
        name='response_studio_list',
    ),
    path(
        'reports/member/<slug:member>/', 
        views.MemberReportPostView.as_view(),
        name='member_reports',
    ),
    # Create Views
    path(
        'add/post/', 
        views.PostCreateView.as_view(),
        name='post_create',
    ),
    path(
        'add/response/<slug:model>-<int:pk>-<slug:members_only>', 
        views.ResponsePostCreateView.as_view(),
        name='response_post_create',
    ),
    path(
        'add/report/', 
        views.ReportPostCreateView.as_view(),
        name='report_post_create',
    ),
    # Update Views
    path(
        'modify/post/<slug:slug>/', 
        views.PostUpdateView.as_view(),
        name='post_update',
    ),
    path(
        'modify/response/<slug:slug>/', 
        views.ResponsePostUpdateView.as_view(),
        name='response_update',
    ),
    # Delete Views
    path(
        'delete/post/<int:pk>/', 
        views.PostDeleteView.as_view(),
        name='post_delete',
    ),
    path(
        'delete/response/<int:pk>/', 
        views.ResponsePostDeleteView.as_view(),
        name='response_delete',
    ),
    path(
        'delete/report/<int:pk>/', 
        views.ResponsePostDeleteView.as_view(),
        name='report_delete',
    ),
    # Publish Views
    path(
        'publish/post/<int:pk>/', 
        views.publish_post_view,
        name='publish_post',
    ),
    path(
        'publish/response/<int:pk>/', 
        views.publish_responsepost_view,
        name='publish_response',
    ),
    # Marshmallow Views
    path(
        '<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_post_view,
        name='post_marshmallow',
    ),
    path(
        'responses/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_responsepost_view,
        name='response_marshmallow',
    ),
]

objects/templates/objects/code_detail_button_bar.html
<div class="row">
  <div class="col-sm">
    <h3 class="code-title">{{ code.title }}</h3>
  </div>
  <div class="col-auto">
    {% if code.owner.pk == request.user.pk %}
      <a href="{% url 'objects:code_delete' code.pk %}">
        <button type="button" class="btn btn-sm  btn-danger float-end">Delete</button>
      </a>
      <a href="{% url 'objects:code_update' code.pk %}">
        <button type="button" class="btn btn-sm btn-warning float-end">Edit</button>
      </a>
      {% if not code.is_public %}
        <a href="{% url 'objects:publish_code' code.pk %}">
          <button type="button" class="btn btn-sm btn-success float-end">Publish</button>
        </a>
      {% endif %}
    {% endif %}
  </div>
</div>
<br>

objects/templates/objects/objects_app_transcoder_settings_form.html
{% extends 'form.html' %}
{% block header_block %}
{% include './objects_form_header.html' %}
{% endblock %}

objects/templates/objects/objectspagesection_detail.html
{% extends "base.html" %}
{% block body_block %}
<div class="container objects-bg">
  <div class="row">
    <div class="col">
      {% if not object.hide_title %}
        <h4 class="objects-page-title">{{ object.title }}</h4>
      {% endif %}
    </div>
    {% if object.owner.pk == request.user.pk %}
      <div class="col-auto">
        <a href="{% url 'objects:objects_page_section_create' %}?order={{ object.next_order }}"><button type="button" class="btn btn-sm btn-primary create-button">+</button></a>
        <a href="{% url 'objects:objects_page_section_update' object.pk %}"><button type="button" class="btn btn-sm btn-warning edit-button">&#9998;</button></a>
        <a href="{% url 'objects:objects_page_section_delete' object.pk %}"><button type="button" class="btn btn-sm btn-danger delete-button">X</button></a>
      </div>
    {% endif %}
  </div>
  <p><i>From the <a href="{% url 'objects:objects_page' %}">{{ profile.title }}</a> landing page.</i></p>
  {% with object as section %}
    {% include 'sections/section.html' %}
  {% endwith %}
  {% if object.is_public %}
    Contributed by <a href="{% url 'objects:member_profile' object.owner.profile.slug %}">{{ object.owner }}</a> on {{ object.publication_date }}<br>
    {% if object.last_modified > object.creation_date %}
      Last updated on {{ object.last_modified }}<br>
    {% endif %}
  {% else %}
    Created by <a href="{% url 'members:member_profile' object.owner.username %}">{{ object.owner }}</a> on {{ object.creation_date }}<br>
  {% endif %}
  <br>
</div>
<br>
{% endblock %}

objects/templates/objects/sound_update_form.html
{% extends 'form.html' %}
{% block header_block %}
{% include './objects_form_header.html' %}
{% endblock %}

objects/templates/objects/tag_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container objects-bg">
  {% if no_public_objects %}
    <p>Nothing has been tagged with "{{ tag }}" yet. Check back soon!</p>
    <br>
  {% else %}
    {% include './tag_detail_header.html' %}
    {% if posts %}
      <h4 class="tag-title">Posts</h4>
      {% for post in posts %}
        {% include 'items/post_list_item.html' %}
      {% endfor %}
      {% if total_posts > list_length %}
        <p>all posts tagged with <a href="{% url 'objects:post_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if articles %}
      <h4 class="tag-title">Articles</h4>
      {% for article in articles %}
        {% include 'items/article_list_item.html' %}
      {% endfor %}
      {% if total_articles > list_length %}
        <p>all articles tagged with <a href="{% url 'objects:article_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if stories %}
      <h4 class="tag-title">Stories</h4>
      {% for story in stories %}
        {% include 'items/story_list_item.html' %}
      {% endfor %}
      {% if total_stories > list_length %}
        <p>all stories tagged with <a href="{% url 'objects:story_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if documents %}
      <h4 class="tag-title">Information</h4>
      {% for document in documents %}
        {% include 'items/document_list_item.html' %}
      {% endfor %}
      {% if total_documents > list_length %}
        <p>all information tagged with <a href="{% url 'objects:support_document_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if visuals %}
      <h4 class="tag-title">Visuals</h4>
      {% for visual in visuals %}
        {% include 'items/visual_item.html' %}
      {% endfor %}
      {% if total_visuals > list_length %}
        <p>all visuals tagged with <a href="{% url 'objects:visual_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <div class="clear"></div>
      <br>
    {% endif %}
    {% if galleries %}
      <h4 class="tag-title">Galleries</h4>
      {% for gallery in galleries %}
        {% include 'items/gallery_list_item.html' %}
      {% endfor %}
      {% if total_galleries > list_length %}
        <p>all galleries tagged with <a href="{% url 'objects:gallery_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if tracks %}
      <h4 class="tag-title">Tracks</h4>
      {% for track in tracks %}
        {% include 'items/track_list_item.html' %}
      {% endfor %}
      {% if total_tracks > list_length %}
        <p>all tracks tagged with <a href="{% url 'objects:track_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if albums %}
      <h4 class="tag-title">Albums</h4>
      {% for album in albums %}
        {% include 'items/album_list_item.html' %}
      {% endfor %}
      {% if total_albums > list_length %}
        <p>all albums tagged with <a href="{% url 'objects:album_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if images %}
      <h4 class="tag-title">Image Files</h4>
      {% for image in images %}
        {% include 'items/image_list_item.html' %}
      {% endfor %}
      {% if total_images > list_length %}
        <p>all images tagged with <a href="{% url 'objects:image_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if sounds %}
      <h4 class="tag-title">Sound Files</h4>
      {% for sound in sounds %}
        {% include 'items/sound_list_item.html' %}
      {% endfor %}
      {% if total_sounds > list_length %}
        <p>all sounds tagged with <a href="{% url 'objects:sound_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if videos %}
      <h4 class="tag-title">Video Files</h4>
      {% for video in videos %}
        {% include 'items/video_list_item.html' %}
      {% endfor %}
      {% if total_videos > list_length %}
        <p>all videos tagged with <a href="{% url 'objects:video_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if codes %}
      <h4 class="tag-title">Code Samples</h4>
      {% for code in codes %}
        {% include 'items/code_list_item.html' %}
      {% endfor %}
      {% if total_codes > list_length %}
        <p>all codes tagged with <a href="{% url 'objects:code_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
    {% if links %}
      <h4 class="tag-title">Links</h4>
      {% for link in links %}
        {% include 'items/link_list_item.html' %}
      {% endfor %}
      {% if total_links > list_length %}
        <p>all links tagged with <a href="{% url 'objects:link_tag' tag.slug %}">"{{ tag }}"</a></p>
      {% endif %}
      <br>
    {% endif %}
  {% endif %}
</div>
<br>
{% endblock %}

objects/templates/objects/tag_list.html
{% extends './objects_list.html' %}
{% block items_block %}
  <form action="{% url 'objects:get_tag_detail' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="col-sm-3">
        <select class="link-list-field" required id="pk" name="pk">&nbps;
          <option value="none" selected disabled hidden>Choose a Tag</option>
          {% for tag in tags %}
            <option value="{{ tag.pk }}">{{ tag }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col">
        <input type="submit" class="btn btn-sm btn-primary" value="Get Tag">
      </div>
    </div>
  </form>
  <br>
  {% if tags.count > 0 %}
    {% include "page_control.html" %}
    <br>
    {% for tag in tags %}
      <span class="objects-tag badge bg-secondary">
        <a href="{% url 'objects:tag_detail' tag.slug %}" class="tag-font">
          {{ tag.key }}{% if tag.value %}: {{ tag.value }}{% endif %}
        </a>
      </span>
    {% endfor %}
    <br><br>
    {% include "page_control.html" %}
  {% else %}
    <p>There are no tags yet. Check back soon!</p>
  {% endif %}
</div>
<br>
{% endblock %}

objects/templates/objects/tag_visuals.html
<!-- Visuals -->
{% if visuals %}
  <h5 class="tag-title">Visuals</h5>
  {% for visual in visuals %}
    {% if visual.is_public or visual.owner.pk == request.user.pk %}
      <a href="{% url 'art:visual_detail' visual.slug %}">
        <div class="art-visual-card float-start" style="background-image:url('{{ visual.image.thumbnail_file.url }}')">
          {% if not visual.is_public %}
            <span class="badge bg-secondary">Unpublished</span>
          {% endif %}
        </div>
      </a>
    {% endif %}
  {% endfor %}
  <div class="clear"></div>
  <br>
  {% if total_visuals > list_length %}
    <p>
      all visuals tagged with <a href="{% url 'objects:visual_tag' tag.slug %}">"{{ tag }}"</a>
    </p>
  {% endif %}
{% endif %}

objects/templates/objects/video_detail_button_bar.html
<div class="row">
  <div class="col-sm">
    <h3 class="video-title">{{ video.title }}</h3>
  </div>
  <div class="col-auto">
    {% if video.owner.pk == request.user.pk %}
      <a href="{% url 'objects:video_delete' video.pk %}">
        <button type="button" class="btn btn-sm  btn-danger float-end">Delete</button>
      </a>
      <a href="{% url 'objects:video_update' video.pk %}">
        <button type="button" class="btn btn-sm btn-warning float-end">Edit</button>
      </a>
      {% if not video.is_public %}
        <a href="{% url 'objects:publish_video' video.pk %}">
          <button type="button" class="btn btn-sm btn-success float-end">Publish</button>
        </a>
      {% endif %}
    {% endif %}
  </div>
</div>
<br>