art/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import art.views as views

app_name = 'art'

urlpatterns = [
    # Music front page
    path(
        '',
        views.ArtPageView.as_view(),
        name="art_page",
    ),
    # Art app profile
    ## Update
    path(
        'profile/update/<int:pk>/', 
        views.ArtAppProfileUpdateView.as_view(),
        name='art_app_profile_update',
    ),
    # Art landing page section views
    ## Create
    path(
        'add/section/', 
        views.ArtPageSectionCreateView.as_view(),
        name='art_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/', 
        views.ArtPageSectionDetailView.as_view(),
        name='art_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.ArtPageSectionUpdateView.as_view(),
        name='art_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/', 
        views.ArtPageSectionDeleteView.as_view(),
        name='art_page_section_delete',
    ),
    # Read Views
    path(
        'galleries/new/',
        views.GalleryListView.as_view(),
        name='new_galleries',
    ),
    path(
        'galleries/',
        views.TopGalleryListView.as_view(),
        name='top_galleries',
    ),
    path(
        'galleries/<slug:slug>/',
        views.GalleryDetailView.as_view(),
        name='gallery_detail',
    ),
    path(
        'visuals/new/',
        views.VisualListView.as_view(),
        name='new_visuals',
    ),
    path(
        'visuals/',
        views.TopVisualListView.as_view(),
        name='top_visuals',
    ),
    path(
        'visuals/<slug:slug>/',
        views.VisualDetailView.as_view(),
        name='visual_detail',
    ),
    path(
        'member/<slug:member>/galleries/',
        views.MemberGalleryView.as_view(),
        name='member_galleries',
    ),
    path(
        'studio/galleries/',
        views.GalleryStudioListView.as_view(),
        name='gallery_studio_list',
    ),
    path(
        'member/<slug:member>/visuals/',
        views.MemberVisualView.as_view(),
        name='member_visuals',
    ),
    path(
        'studio/articles/',
        views.VisualStudioListView.as_view(),
        name='visual_studio_list',
    ),
    # Create Views
    path(
        'add/gallery/',
        views.GalleryCreateView.as_view(),
        name='gallery_create',
    ),
    path(
        'add/visual/',
        views.VisualCreateView.as_view(),
        name='visual_create',
    ),
    # Update Views
    path(
        'modify/gallery/<slug:slug>/',
        views.GalleryUpdateView.as_view(),
        name='gallery_update',
    ),
    path(
        'modify/visual/<slug:slug>/',
        views.VisualUpdateView.as_view(),
        name='visual_update',
    ),
    # Delete Views
    path(
        'delete/gallery/<int:pk>/',
        views.GalleryDeleteView.as_view(),
        name='gallery_delete',
    ),
    path(
        'delete/visual/<int:pk>/',
        views.VisualDeleteView.as_view(),
        name='visual_delete',
    ),
    # Publish Views
    path(
        'publish/gallery/<int:pk>/',
        views.publish_gallery_view,
        name='publish_gallery',
    ),
    path(
        'publish/visual/<int:pk>/',
        views.publish_visual_view,
        name='publish_visual',
    ),
    # Marshmallow Views
    path(
        'galleries/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_gallery_view,
        name='gallery_marshmallow',
    ),
    path(
        'visuals/<int:pk>/add-marshmallow',
        views.add_marshmallow_to_visual_view,
        name='visual_marshmallow',
    ),
]

members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
import members.views as views

app_name = "members"
urlpatterns = [
    # Members landing page
    path(
        '',
        views.MembersPageView.as_view(),
        name="members_page",
    ),
    # Members app profile
    ## Update
    path(
        'app-profile/update/<int:pk>/', 
        views.MembersAppProfileUpdateView.as_view(),
        name='members_app_profile_update',
    ),
    # Members landing page section views
    ## Create
    path(
        'add/section/', 
        views.MembersPageSectionCreateView.as_view(),
        name='members_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.MembersPageSectionDetailView.as_view(),
        name='members_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.MembersPageSectionUpdateView.as_view(),
        name='members_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.MembersPageSectionDeleteView.as_view(),
        name='members_page_section_delete',
    ),
    # Member profile
    ## Update
    path(
        'profile/update/<int:pk>/',
        views.MemberProfileUpdateView.as_view(),
        name='member_profile_update',
    ),
    path(
        'profile/settings/update/<int:pk>/',
        views.MemberProfileSettingsUpdateView.as_view(),
        name='member_profile_settings_update',
    ),
    # Member profile page section views
    ## Create
    path(
        'profile/add/section/',
        views.MemberProfileSectionCreateView.as_view(),
        name='member_profile_section_create',
    ),
    ## Detail
    path(
        'profile/sections/<int:pk>/',
        views.MemberProfileSectionDetailView.as_view(),
        name='member_profile_section_detail',
    ),
    ## Update
    path(
        'profile/update/section/<int:pk>/', 
        views.MemberProfileSectionUpdateView.as_view(),
        name='member_profile_section_update',
    ),
    ## Delete
    path(
        'profile/delete/section/<int:pk>/',
        views.MemberProfileSectionDeleteView.as_view(),
        name='member_profile_section_delete',
    ),
    ## List
    path(
        'all/', 
        views.MemberListView.as_view(),
        name='member_list',
    ),
    path(
        'contributors/', 
        views.ContributorListView.as_view(),
        name='contributor_list',
    ),
    path(
        'artists/', 
        views.ArtistListView.as_view(),
        name='artist_list',
    ),
    path(
        'musicians/', 
        views.MusicianListView.as_view(),
        name='musician_list',
    ),
    path(
        'writers/', 
        views.WriterListView.as_view(),
        name='writer_list',
    ),
    path(
        'staff/', 
        views.StaffListView.as_view(),
        name='staff_list',
    ),
    # Studio
    path(
        'studio/',
        views.StudioView.as_view(),
        name='studio',
    ),
    path(
        '<slug:slug>/profile/', 
        views.MemberProfileUpdateView.as_view(),
        name='member_profile_update',
    ),
    path(
        'join-us/<slug:slug>/', 
        views.InviteLinkDetailView.as_view(),
        name='invite_link_detail',
    ),
    path(
        'register/<slug:invite>/', 
        views.member_registration,
        name='member_registration',
    ),
    # Profile page
    path(
        '<slug:slug>/', 
        views.MemberProfileView.as_view(),
        name='member_profile',
    ),
]

music/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
import music.views as views  

app_name = 'music'

urlpatterns = [
    # Music landing page
    path(
        '',
        views.MusicPageView.as_view(),
        name="music_page",
    ),
    # Music app profile
    ## Update
    path(
        'profile/update/<int:pk>/', 
        views.MusicAppProfileUpdateView.as_view(),
        name='music_app_profile_update',
    ),
    # Music landing page section views
    ## Create
    path(
        'add/section/', 
        views.MusicPageSectionCreateView.as_view(),
        name='music_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.MusicPageSectionDetailView.as_view(),
        name='music_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/', 
        views.MusicPageSectionUpdateView.as_view(),
        name='music_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.MusicPageSectionDeleteView.as_view(),
        name='music_page_section_delete',
    ),
    # Read Views
    path(
        'albums/new/',
        views.AlbumListView.as_view(),
        name='new_albums',
    ),
    path(
        'albums/',
        views.TopAlbumListView.as_view(),
        name='top_albums',
    ),
    path(
        'albums/<slug:slug>/',
        views.AlbumDetailView.as_view(),
        name='album_detail',
    ),
    path(
        'tracks/new/',
        views.TrackListView.as_view(),
        name='new_tracks',
    ),
    path(
        'tracks/',
        views.TopTrackListView.as_view(),
        name='top_tracks',
    ),
    path(
        'tracks/<slug:slug>/',
        views.TrackDetailView.as_view(),
        name='track_detail',
    ),
    path(
        'member/<slug:member>/albums/',
        views.MemberAlbumView.as_view(),
        name='member_albums',
    ),
    path(
        'studio/albums/',
        views.AlbumStudioListView.as_view(),
        name='album_studio_list',
    ),
    path(
        'member/<slug:member>/tracks/',
        views.MemberTrackView.as_view(),
        name='member_tracks',
    ),
    path(
        'studio/tracks/',
        views.TrackStudioListView.as_view(),
        name='track_studio_list',
    ),
    # Create Views
    path(
        'add/album/',
        views.AlbumCreateView.as_view(),
        name='album_create',
    ),
    path(
        'add/track/',
        views.TrackCreateView.as_view(),
        name='track_create',
    ),
    # Update Views
    path(
        'modify/album/<slug:slug>/',
        views.AlbumUpdateView.as_view(),
        name='album_update',
    ),
    path(
        'modify/track/<slug:slug>/',
        views.TrackUpdateView.as_view(),
        name='track_update',
    ),
    # Delete Views
    path(
        'delete/album/<int:pk>/',
        views.AlbumDeleteView.as_view(),
        name='album_delete',
    ),
    path(
        'delete/track/<int:pk>/',
        views.TrackDeleteView.as_view(),
        name='track_delete',
    ),
    # Publish Views
    path(
        'publish/album/<int:pk>/',
        views.publish_album_view,
        name='publish_album',
    ),
    path(
        'publish/track/<int:pk>/',
        views.publish_track_view,
        name='publish_track',
    ),
    # Marshmallow Views
    path(
        'albums/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_album_view,
        name='album_marshmallow',
    ),
    path(
        'tracks/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_track_view,
        name='track_marshmallow',
    ),
]

posts/urls.py
from django.urls import path
import posts.views as views

app_name= "posts"

urlpatterns = [
    # Posts landing page
    path(
        '',
        views.PostsPageView.as_view(),
        name="posts_page",
    ),
    # Posts app profile
    ## Update
    path(
        'profile/update/<int:pk>/',
        views.PostsAppProfileUpdateView.as_view(),
        name='posts_app_profile_update',
    ),
    # Posts landing page section views
    ## Create
    path(
        'add/section/',
        views.PostsPageSectionCreateView.as_view(),
        name='posts_page_section_create',
    ),
    ## Detail
    path(
        'sections/<int:pk>/',
        views.PostsPageSectionDetailView.as_view(),
        name='posts_page_section_detail',
    ),
    ## Update
    path(
        'update/section/<int:pk>/',
        views.PostsPageSectionUpdateView.as_view(),
        name='posts_page_section_update',
    ),
    ## Delete
    path(
        'delete/section/<int:pk>/',
        views.PostsPageSectionDeleteView.as_view(),
        name='posts_page_section_delete',
    ),
    # Read Views
    path(
        'new/', 
        views.PostListView.as_view(),
        name='public_posts',
    ),
    path(
        'top/', 
        views.TopPostListView.as_view(),
        name='top_posts',
    ),
    path(
        'responses/', 
        views.ResponsePostListView.as_view(),
        name='public_responses',
    ),
    path(
        'responses/top/', 
        views.TopResponsePostListView.as_view(),
        name='top_responses',
    ),
    path(
        'reports/', 
        views.ReportPostListView.as_view(),
        name='reports',
    ),
    path(
        '<slug:slug>/', 
        views.PostDetailView.as_view(),
        name='post_detail',
    ),
    path(
        'responses/<slug:slug>/', 
        views.ResponsePostDetailView.as_view(),
        name='response_detail',
    ),
    path(
        'reports/<int:pk>/', 
        views.ReportPostDetailView.as_view(),
        name='report_detail',
    ),
    # Member Specific Views
    path(
        'member/<slug:member>/', 
        views.MemberPostView.as_view(),
        name='member_posts',
    ),
    path(
        'studio/posts/',
        views.PostStudioListView.as_view(),
        name='post_studio_list',
    ),
    path(
        'responses/member/<slug:member>/', 
        views.MemberResponsePostView.as_view(),
        name='member_responses',
    ),
    path(
        'studio/responses/',
        views.ResponsePostStudioListView.as_view(),
        name='response_studio_list',
    ),
    path(
        'reports/member/<slug:member>/', 
        views.MemberReportPostView.as_view(),
        name='member_reports',
    ),
    # Create Views
    path(
        'add/post/', 
        views.PostCreateView.as_view(),
        name='post_create',
    ),
    path(
        'add/response/<slug:model>-<int:pk>-<slug:members_only>', 
        views.ResponsePostCreateView.as_view(),
        name='response_post_create',
    ),
    path(
        'add/report/', 
        views.ReportPostCreateView.as_view(),
        name='report_post_create',
    ),
    # Update Views
    path(
        'modify/post/<slug:slug>/', 
        views.PostUpdateView.as_view(),
        name='post_update',
    ),
    path(
        'modify/response/<slug:slug>/', 
        views.ResponsePostUpdateView.as_view(),
        name='response_update',
    ),
    # Delete Views
    path(
        'delete/post/<int:pk>/', 
        views.PostDeleteView.as_view(),
        name='post_delete',
    ),
    path(
        'delete/response/<int:pk>/', 
        views.ResponsePostDeleteView.as_view(),
        name='response_delete',
    ),
    path(
        'delete/report/<int:pk>/', 
        views.ResponsePostDeleteView.as_view(),
        name='report_delete',
    ),
    # Publish Views
    path(
        'publish/post/<int:pk>/', 
        views.publish_post_view,
        name='publish_post',
    ),
    path(
        'publish/response/<int:pk>/', 
        views.publish_responsepost_view,
        name='publish_response',
    ),
    # Marshmallow Views
    path(
        '<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_post_view,
        name='post_marshmallow',
    ),
    path(
        'responses/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_responsepost_view,
        name='response_marshmallow',
    ),
]

templates/items/article_list_item.html
<li class="list-group-item documentation-list-li">
  {% with 'documentation-item-list-image' as t_css and article.get_thumbnail as thumbnail and 'documentation-title' as h_css and article.title as title and article.get_absolute_url as url and article.meta_description as text and article.is_public as public %}
    {% include 'items/list_item.html' %}
  {% endwith %}
</li>

templates/items/detail_item.html
<div class="row">
  <div class="col-sm-auto float-start">
    {% block thumbnail_block %}{% endblock %}
  </div>
  <div class="col">
    {% block title_block %}{% endblock %}
    {% block meta_data_block %}{% endblock %}
  </div>
</div>
<p>{% block text_block %}{% endblock %}</p>

templates/items/document_item.html
{% extends 'items/detail_item.html' %}
{% block thumbnail_block %}
  <div class="documentation-item-detail-image" style="background-image:url('{{ document.get_thumbnail }}')"></div>
{% endblock %}
{% block title_block %}
  <h5 class="documentation-title">
    <a href="{% url 'documentation:support_document_detail' document.slug %}">
      {{ document.title }}
    </a>
  </h5>
{% endblock %}
{% block meta_data_block %}
  <p>
    Documented by <a href="{% url 'members:member_profile' document.owner.username %}"><span class="index-heading-span">{{ document.owner }}</span></a><br>{% if document.last_modified %}Last updated on <span class="index-header-span">{{ document.last_modified|date:"M d, Y" }}</span>{% elif document.publication_date %}Published on <span class="index-heading-span">{{ document.publication_date|date:"M d, Y" }}</span>{% endif %}
  </p>
{% endblock %}
{% block text_block %}{{ document.meta_description }}{% endblock %}
{% block tags_block %}
  {% if document.members_only %}
    <span class="badge bg-warning">Members Only</span>
  {% endif %}
  {% if not document.is_public %}
    <span class="badge bg-dark">Unpublished</span>
  {% endif %}
  {% if document.tags.all.count > 0 %}
    {% with document as object %}
      {% include 'objects/object_tags.html' %}
    {% endwith %}
  {% endif %}
{% endblock %}

templates/items/document_list_item.html
<li class="list-group-item documentation-list-li">
  {% with 'documentation-item-list-image' as t_css and document.get_thumbnail as thumbnail and 'documentation-title' as h_css and document.title as title and document.get_absolute_url as url and document.meta_description as text and document.is_public as public %}
    {% include 'items/list_item.html' %}
  {% endwith %}
</li>

templates/items/image_list_item.html
<li class="list-group-item objects-list-li">
  {% with image.thumbnail_file.url as thumbnail and image.title|truncatechars:64 as title and image.get_absolute_url as url  and 'objects-title' as h_css and image.text as text %}
    {% include 'items/studio_list_item.html' %}
  {% endwith %}
</li>

templates/items/member_list_item.html
<li class="list-group-item art-list-li">
  <div class="row">
    <div class="col-">
      {% if member.profile.image %}
        <div class="members-list-image" style="background-image:url('{{ member.profile.image.thumbnail_file.url }}')"></div>
      {% else %}
        <div class="members-list-image" style="background-image:url('/static/icon.webp')"></div>
      {% endif %}
    </div>
    <div class="col-sm">
      <h6 class="members-title">
        <strong><a href="{% url 'members:member_profile' member.username %}">
          {{ member }}
        </a></strong>
      </h6>
      <p>
        Member since <span class="index-heading-span">{{ member.date_joined|date:"M d, Y" }}</span><br>
        {% include './member_badges.html' %}
      </p>
    </div>
  </div>
</li>

templates/items/post_item.html
{% extends 'items/detail_item.html' %}
{% block thumbnail_block %}
  <div class="posts-item-detail-image" style="background-image:url('{{ post.get_thumbnail }}')"></div>
{% endblock %}
{% block title_block %}
  <h6 class="posts-title">
    <strong><a href="{% url 'posts:post_detail' post.slug %}">
      {{ post.title }}
    </a></strong>
  </h6>
{% endblock %}
{% block meta_data_block %}
  <p>
    Posted by <a href="{% url 'members:member_profile' post.owner.username %}"><span class="index-heading-span">{{ post.owner }}</span></a>{% if post.publication_date %}<br><span class="index-heading-span">{{ post.publication_date|date:"M d, Y" }}</span>{% endif %}{% if post.location %} from <span class="index-heading-span">{{ post.location }}</span>{% endif %}
  </p>
{% endblock %}
{% block text_block %}{{ post.meta_description }}{% endblock %}
{% block tags_block %}
  {% if not post.is_public %}
    <span class="badge bg-dark">Unpublished</span>
  {% endif %}
  {% if post.members_only %}
    <span class="badge bg-warning">Members Only</span>
  {% endif %}
  {% if post.tags.all.count > 0 %}
  {% with post as object %}
    {% include 'objects/object_tags.html' %}
  {% endwith %}
  {% endif %}
{% endblock %}

templates/items/post_list_item.html
<li class="list-group-item posts-list-li">
  {% with 'posts-item-list-image' as t_css and post.get_thumbnail as thumbnail and 'posts-title' as h_css and post.title as title and post.get_absolute_url as url and post.meta_description as text and post.is_public as public %}
    {% include 'items/list_item.html' %}
  {% endwith %}
</li>

templates/items/re_links.html
{% if response.post %}
  <i>Re: <a href="{% url 'posts:post_detail' response.post.slug %}">{{ response.post }}</a></i><br>
{% elif response.article %}
  <i>Re: <a href="{% url 'documentation:article_detail' response.article.slug %}">{{ response.article }}</a></i><br>
{% elif response.story %}
  <i>Re: <a href="{% url 'documentation:story_detail' response.story.slug %}">{{ response.story }}</a></i><br>
{% elif response.document %}
  <i>Re: <a href="{% url 'documentation:support_document_detail' response.document.slug %}">{{ response.document }}</a></i><br>
{% elif response.visual %}
  <i>Re: <a href="{% url 'art:visual_detail' response.visual.slug %}">{{ response.visual }}</a></i><br>
{% elif response.gallery %}
  <i>Re: <a href="{% url 'art:gallery_detail' response.gallery.slug %}">{{ response.gallery }}</a></i><br>
{% elif response.track %}
  <i>Re: <a href="{% url 'music:track_detail' response.track.slug %}">{{ response.track }}</a></i><br>
{% elif response.album %}
  <i>Re: <a href="{% url 'music:album_detail' response.album.slug %}">{{ response.album }}</a></i><br>
{% else %}
  <i>This is a Response to content that was removed by its publisher</i><br>
{% endif %}

templates/items/response_item.html
{% extends 'items/detail_item.html' %}
{% block thumbnail_block %}
  <div class="posts-item-detail-image" style="background-image:url('{{ response.get_thumbnail }}')"></div>
{% endblock %}
{% block title_block %}
  <h6 class="responses-title">
    <strong><a href="{% url 'posts:response_detail' response.slug %}">
      {{ response.title }}
    </a></strong>
  </h6>
{% endblock %}
{% block meta_data_block %}
  <p>
    {% include './re_links.html' %}
    Posted by <a href="{% url 'members:member_profile' response.owner.username %}"><span class="index-heading-span">{{ response.owner }}</span></a>{% if response.publication_date %} on <span class="index-heading-span">{{ response.publication_date|date:"M d, Y" }}</span>{% endif %}{% if response.location %} from <span class="index-heading-span">{{ response.location }}</span>{% endif %}
  </p>
{% endblock %}
{% block text_block %}{{ response.text|truncatechars:155 }}{% endblock %}
{% block tags_block %}
  {% if not response.is_public %}
    <span class="badge bg-dark">Unpublished</span>
  {% endif %}
  {% if response.members_only %}
    <span class="badge bg-warning">Members Only</span>
  {% endif %}
  {% if response.tags.all.count > 0 %}
  {% with response as object %}
    {% include 'objects/object_tags.html' %}
  {% endwith %}
  {% endif %}
{% endblock %}

templates/items/response_list_item.html
{% extends 'items/detail_item.html' %}
{% block thumbnail_block %}
  <div class="posts-item-detail-image" style="background-image:url('{{ response.get_thumbnail }}')"></div>
{% endblock %}
{% block title_block %}
  <h5 class="posts-title">
    <a href="{% url 'posts:response_detail' response.slug %}">
      {{ response.title }}
    </a>
  </h5>
{% endblock %}
{% block meta_data_block %}
  <p>
    {% include './re_links.html' %}
    {{ response.text|truncatechars:155 }}
  </p>
{% endblock %}
{% block tags_block %}
  {% if not response.is_public %}
    <span class="badge bg-dark">Unpublished</span>
  {% endif %}
  {% if response.members_only %}
    <span class="badge bg-warning">Members Only</span>
  {% endif %}
  {% if response.tags.all.count > 0 %}
  {% with response as object %}
    {% include 'objects/object_tags.html' %}
  {% endwith %}
  {% endif %}
{% endblock %}

templates/items/sound_list_item.html
<li class="list-group-item objects-list-li">
  {% with sound.title|truncatechars:64 as title and sound.get_absolute_url as url and 'objects-title' as h_css and '&#128266;' as icon and sound.text as text %}
    {% include 'items/studio_list_item.html' %}
  {% endwith %}
</li>

templates/items/story_list_item.html
<li class="list-group-item documentation-list-li">
  {% with 'documentation-item-list-image' as t_css and story.get_thumbnail as thumbnail and 'documentation-title' as h_css and story.title as title and story.get_absolute_url as url and story.meta_description as text and story.is_public as public %}
    {% include 'items/list_item.html' %}
  {% endwith %}
</li>

templates/items/visual_tile.html
<a href="{% url 'art:visual_detail' visual.slug %}">
  {% if visual.image.thumbnail_file %}
    <div class="float-start art-visual-card" style="background-image:url('{{ visual.image.thumbnail_file.url }}">
      {% if not visual.is_public %}
        <span class="badge bg-secondary">Unpublished</span>
      {% endif %}
    </div>
  {% else %}
    <span class="visuals-piece-card-title">{{ visual.title }}</span>
    <span class="visuals-piece-card-title">Click here to see the Visual</span>
  {% endif %}
</a>